name: FakeVanish
main: fakeplugins.fakeplugins.fakevanish.FakeVanish
version: ${project.version}
api-version: 1.16
author: MinuteEdge

commands:
  va:
    description: Переключить fake vanish
    usage: /va
    aliases: [fv, fakevanish]

permissions:
  fakevanish.helper:
    description: Helper может использовать команду и видеть скрытых
    default: false
  fakevanish.sthelper:
    description: Старший helper
    default: false
  fakevanish.moder:
    description: Moderator
    default: false
  fakevanish.stmoder:
    description: Старший moderator
    default: false
  fakevanish.glmoder:
    description: Главный moderator
    default: false
  fakevanish.zam:
    description: Заместитель
    default: false
  fakevanish.curator:
    description: Curator
    default: false
  fakevanish.stcurator:
    description: Старший curator
    default: false
  fakevanish.glcurator:
    description: Главный curator
    default: false
  fakevanish.mladm:
    description: Младший администратор
    default: false
